### ISSUE TITLE
Cannot read properties of undefined (reading 'type') with DnD5e system.

### ISSUE THREAD

**Issue by Littlepanda115** [shemetz/roll-from-compendium#25] opened 2024-01-29 09:44 UTC
I can't see the creation of a dummy actor, nor a means to create the dummy actor myself. Unfortunately, the lack of creation for this might be the cause of this error. There doesn't seem to be a way to manually trigger the creation of this actor, or do it myself.

When trying to send a feature, item, spell, etc, to the chat, nothing appears.

This issue persists with all modules deactivated except this one. Interestingly, the 'Send Image to Chat' button for characters does work, however. I'm unsure if this is somehow an issue only happening to myself, but with the issue persisting with no other modules active, it might be due to recent versions of the DnD5e System or Foundry itself, as I am using the most recent version of both as of the creation of this issue.

Here is a screenshot of the error:

![image](https://github.com/shemetz/roll-from-compendium/assets/55049376/afaa1861-4d20-4ea0-ab7d-96b1177141f2)

**Comment by shemetz** [comment] 2024-01-29 12:56
Thank you!  Apparently this was broken for almost 4 months... -_-

**Comment by shemetz** [comment] 2024-01-29 12:58
Should be fixed in v1.7.2, I didn't even test this fix because it was so obvious from looking at the code but I'd appreciate if you can verify that it works now.

**Closed by shemetz** 2024-01-29 12:58 UTC

**Comment by shemetz** [comment] 2024-01-30 07:23
Actually, can you show me a screenshot of what happens to you right now when you use the module to post a few spells, weapons, and features, for PCs and/or NPCs, one of each?

Because I do see descriptions now that I'm trying to do it:

![image](https://github.com/shemetz/roll-from-compendium/assets/6516621/00876d93-6554-4524-99ec-d061aa1f22dd)

Am I using an old version somehow?

**Comment by shemetz** [comment] 2024-01-30 07:57
> Sorry for the delay and format, I am having to screenshot a Parsec connection to my server laptop from my phone as I'm out at the gym, lol.

Wow, please don't feel obligated to respond so quickly :D  I'll be happy even if you wait multiple days before responding, so no hurry (but thank you for the good responses).

It does seem like there's some bug in your setup that prevents those descriptions from showing up, but, it *could* be a bug with my own module too, making it somehow fail to work in some cases.

I can confirm that I do not have an "info" button like that in any feature or spell;  I remember it existing in the past, so I think it was removed, indeed.

Once you have the time, I would appreciate one or more of the following troubleshooting steps:

1. Disable all modules and then try the in-sheet button again
2. Disable all other modules except this one and then try its button again
3. Check the console (F12) to see if any big error messages pop up;  may need to sift through them if there are many, and search for one that mentions this module or mentions descriptions
4. Give me a link to your world and login details as a temporary account, to directly test in my own browser (if you're okay with that)

I would definitely expect some bug to be happening, from that screenshot, because I can see that there's a small empty space between two horizontal lines within the "Hateful Eyes" chat message.  That space is exactly where the description is expected to appear.
